# Generated by Django 5.2.3 on 2025-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
