# Generated by Django 5.2.3 on 2025-06-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_used',
        ),
    ]
