# Generated by Django 5.2.3 on 2025-06-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('products_list', 'Products List'), ('marketing_list', 'Marketing List'), ('order_list', 'Order List'), ('media_plans', 'Media Plans'), ('offer_pricing_skus', 'Offer Pricing SKUs'), ('clients', 'Clients'), ('suppliers', 'Suppliers'), ('customer_support', 'Customer Support'), ('sales_reports', 'Sales Reports'), ('finance_accounting', 'Finance & Accounting')], max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField()),
                ('new_text', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='adminpanel.comment')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('products_list', 'Products List'), ('marketing_list', 'Marketing List'), ('order_list', 'Order List'), ('media_plans', 'Media Plans'), ('offer_pricing_skus', 'Offer Pricing SKUs'), ('clients', 'Clients'), ('suppliers', 'Suppliers'), ('customer_support', 'Customer Support'), ('sales_reports', 'Sales Reports'), ('finance_accounting', 'Finance & Accounting')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'page')},
            },
        ),
    ]
