# Generated by Django 5.2.3 on 2025-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_commenthistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthistory',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('edited', 'Edited'), ('deleted', 'Deleted')], default='added', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commenthistory',
            name='new_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commenthistory',
            name='old_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
